/*
 * This file is generated by jOOQ.
 */
package com.punch.entity;


import com.punch.entity.tables.OaUser;
import com.punch.entity.tables.SysUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>punch</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OA_USER_OA_USER_001 = Indexes0.OA_USER_OA_USER_001;
    public static final Index SYS_USER_IDX_SYS_USER_001 = Indexes0.SYS_USER_IDX_SYS_USER_001;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index OA_USER_OA_USER_001 = Internal.createIndex("oa_user_001", OaUser.OA_USER, new OrderField[] { OaUser.OA_USER.LOGIN_ID }, false);
        public static Index SYS_USER_IDX_SYS_USER_001 = Internal.createIndex("idx_sys_user_001", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.PHONE }, false);
    }
}
