/*
 * This file is generated by jOOQ.
 */
package com.punch.entity;


import com.punch.entity.tables.OaPunchLog;
import com.punch.entity.tables.OaUser;
import com.punch.entity.tables.SysQuartz;
import com.punch.entity.tables.SysUser;
import com.punch.entity.tables.records.OaPunchLogRecord;
import com.punch.entity.tables.records.OaUserRecord;
import com.punch.entity.tables.records.SysQuartzRecord;
import com.punch.entity.tables.records.SysUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>punch</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OaPunchLogRecord> KEY_OA_PUNCH_LOG_PRIMARY = UniqueKeys0.KEY_OA_PUNCH_LOG_PRIMARY;
    public static final UniqueKey<OaUserRecord> KEY_OA_USER_PRIMARY = UniqueKeys0.KEY_OA_USER_PRIMARY;
    public static final UniqueKey<SysQuartzRecord> KEY_SYS_QUARTZ_PRIMARY = UniqueKeys0.KEY_SYS_QUARTZ_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<OaPunchLogRecord> KEY_OA_PUNCH_LOG_PRIMARY = Internal.createUniqueKey(OaPunchLog.OA_PUNCH_LOG, "KEY_oa_punch_log_PRIMARY", new TableField[] { OaPunchLog.OA_PUNCH_LOG.ID }, true);
        public static final UniqueKey<OaUserRecord> KEY_OA_USER_PRIMARY = Internal.createUniqueKey(OaUser.OA_USER, "KEY_oa_user_PRIMARY", new TableField[] { OaUser.OA_USER.ID }, true);
        public static final UniqueKey<SysQuartzRecord> KEY_SYS_QUARTZ_PRIMARY = Internal.createUniqueKey(SysQuartz.SYS_QUARTZ, "KEY_sys_quartz_PRIMARY", new TableField[] { SysQuartz.SYS_QUARTZ.JOB_KEY }, true);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_PRIMARY", new TableField[] { SysUser.SYS_USER.ID }, true);
    }
}
