/*
 * This file is generated by jOOQ.
 */
package com.punch.entity;


import com.punch.entity.tables.OaPunchLog;
import com.punch.entity.tables.OaUser;
import com.punch.entity.tables.SysQuartz;
import com.punch.entity.tables.SysUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Punch extends SchemaImpl {

    private static final long serialVersionUID = -126969579;

    /**
     * The reference instance of <code>punch</code>
     */
    public static final Punch PUNCH = new Punch();

    /**
     * The table <code>punch.oa_punch_log</code>.
     */
    public final OaPunchLog OA_PUNCH_LOG = OaPunchLog.OA_PUNCH_LOG;

    /**
     * The table <code>punch.oa_user</code>.
     */
    public final OaUser OA_USER = OaUser.OA_USER;

    /**
     * 定时任务
     */
    public final SysQuartz SYS_QUARTZ = SysQuartz.SYS_QUARTZ;

    /**
     * 用户表
     */
    public final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * No further instances allowed
     */
    private Punch() {
        super("punch", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            OaPunchLog.OA_PUNCH_LOG,
            OaUser.OA_USER,
            SysQuartz.SYS_QUARTZ,
            SysUser.SYS_USER);
    }
}
