/*
 * This file is generated by jOOQ.
 */
package com.punch.entity;


import com.punch.entity.tables.OaPunchLog;
import com.punch.entity.tables.OaUser;
import com.punch.entity.tables.SysQuartz;
import com.punch.entity.tables.SysUser;


/**
 * Convenience access to all tables in punch
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>punch.oa_punch_log</code>.
     */
    public static final OaPunchLog OA_PUNCH_LOG = OaPunchLog.OA_PUNCH_LOG;

    /**
     * The table <code>punch.oa_user</code>.
     */
    public static final OaUser OA_USER = OaUser.OA_USER;

    /**
     * 定时任务
     */
    public static final SysQuartz SYS_QUARTZ = SysQuartz.SYS_QUARTZ;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;
}
