/*
 * This file is generated by jOOQ.
 */
package com.punch.entity.tables.records;


import com.punch.entity.tables.OaUser;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OaUserRecord extends UpdatableRecordImpl<OaUserRecord> implements Record15<String, String, String, String, String, String, String, String, String, String, Integer, String, LocalDateTime, Integer, String> {

    private static final long serialVersionUID = -701928576;

    /**
     * Setter for <code>punch.oa_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>punch.oa_user.id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>punch.oa_user.login_id</code>. oa登录名
     */
    public void setLoginId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>punch.oa_user.login_id</code>. oa登录名
     */
    @Size(max = 16)
    public String getLoginId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>punch.oa_user.password</code>. oa密码
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>punch.oa_user.password</code>. oa密码
     */
    @Size(max = 16)
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>punch.oa_user.mobile</code>. 手机号
     */
    public void setMobile(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>punch.oa_user.mobile</code>. 手机号
     */
    @Size(max = 16)
    public String getMobile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>punch.oa_user.client_model</code>. 手机型号
     */
    public void setClientModel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>punch.oa_user.client_model</code>. 手机型号
     */
    @Size(max = 16)
    public String getClientModel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>punch.oa_user.device_name</code>. 设备名称
     */
    public void setDeviceName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>punch.oa_user.device_name</code>. 设备名称
     */
    @Size(max = 16)
    public String getDeviceName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>punch.oa_user.device_id</code>. 设备id
     */
    public void setDeviceId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>punch.oa_user.device_id</code>. 设备id
     */
    @Size(max = 128)
    public String getDeviceId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>punch.oa_user.os_version</code>. 操作系统版本
     */
    public void setOsVersion(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>punch.oa_user.os_version</code>. 操作系统版本
     */
    @Size(max = 16)
    public String getOsVersion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>punch.oa_user.oa_user_id</code>. oa用户id
     */
    public void setOaUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>punch.oa_user.oa_user_id</code>. oa用户id
     */
    @Size(max = 16)
    public String getOaUserId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>punch.oa_user.oa_user_name</code>. 姓名
     */
    public void setOaUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>punch.oa_user.oa_user_name</code>. 姓名
     */
    @Size(max = 16)
    public String getOaUserName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>punch.oa_user.enable</code>. 是否启用 1启用 0停用
     */
    public void setEnable(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>punch.oa_user.enable</code>. 是否启用 1启用 0停用
     */
    public Integer getEnable() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>punch.oa_user.push_id</code>. 通知推送id
     */
    public void setPushId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>punch.oa_user.push_id</code>. 通知推送id
     */
    @Size(max = 255)
    public String getPushId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>punch.oa_user.create_time</code>. 新增时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>punch.oa_user.create_time</code>. 新增时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>punch.oa_user.client_type</code>. 设备类型 2 IOS、3安卓
     */
    public void setClientType(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>punch.oa_user.client_type</code>. 设备类型 2 IOS、3安卓
     */
    public Integer getClientType() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>punch.oa_user.loginUUID</code>. 登录uuid
     */
    public void setLoginuuid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>punch.oa_user.loginUUID</code>. 登录uuid
     */
    @Size(max = 36)
    public String getLoginuuid() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, Integer, String, LocalDateTime, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, Integer, String, LocalDateTime, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OaUser.OA_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return OaUser.OA_USER.LOGIN_ID;
    }

    @Override
    public Field<String> field3() {
        return OaUser.OA_USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return OaUser.OA_USER.MOBILE;
    }

    @Override
    public Field<String> field5() {
        return OaUser.OA_USER.CLIENT_MODEL;
    }

    @Override
    public Field<String> field6() {
        return OaUser.OA_USER.DEVICE_NAME;
    }

    @Override
    public Field<String> field7() {
        return OaUser.OA_USER.DEVICE_ID;
    }

    @Override
    public Field<String> field8() {
        return OaUser.OA_USER.OS_VERSION;
    }

    @Override
    public Field<String> field9() {
        return OaUser.OA_USER.OA_USER_ID;
    }

    @Override
    public Field<String> field10() {
        return OaUser.OA_USER.OA_USER_NAME;
    }

    @Override
    public Field<Integer> field11() {
        return OaUser.OA_USER.ENABLE;
    }

    @Override
    public Field<String> field12() {
        return OaUser.OA_USER.PUSH_ID;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return OaUser.OA_USER.CREATE_TIME;
    }

    @Override
    public Field<Integer> field14() {
        return OaUser.OA_USER.CLIENT_TYPE;
    }

    @Override
    public Field<String> field15() {
        return OaUser.OA_USER.LOGINUUID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLoginId();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getMobile();
    }

    @Override
    public String component5() {
        return getClientModel();
    }

    @Override
    public String component6() {
        return getDeviceName();
    }

    @Override
    public String component7() {
        return getDeviceId();
    }

    @Override
    public String component8() {
        return getOsVersion();
    }

    @Override
    public String component9() {
        return getOaUserId();
    }

    @Override
    public String component10() {
        return getOaUserName();
    }

    @Override
    public Integer component11() {
        return getEnable();
    }

    @Override
    public String component12() {
        return getPushId();
    }

    @Override
    public LocalDateTime component13() {
        return getCreateTime();
    }

    @Override
    public Integer component14() {
        return getClientType();
    }

    @Override
    public String component15() {
        return getLoginuuid();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLoginId();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getMobile();
    }

    @Override
    public String value5() {
        return getClientModel();
    }

    @Override
    public String value6() {
        return getDeviceName();
    }

    @Override
    public String value7() {
        return getDeviceId();
    }

    @Override
    public String value8() {
        return getOsVersion();
    }

    @Override
    public String value9() {
        return getOaUserId();
    }

    @Override
    public String value10() {
        return getOaUserName();
    }

    @Override
    public Integer value11() {
        return getEnable();
    }

    @Override
    public String value12() {
        return getPushId();
    }

    @Override
    public LocalDateTime value13() {
        return getCreateTime();
    }

    @Override
    public Integer value14() {
        return getClientType();
    }

    @Override
    public String value15() {
        return getLoginuuid();
    }

    @Override
    public OaUserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public OaUserRecord value2(String value) {
        setLoginId(value);
        return this;
    }

    @Override
    public OaUserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public OaUserRecord value4(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public OaUserRecord value5(String value) {
        setClientModel(value);
        return this;
    }

    @Override
    public OaUserRecord value6(String value) {
        setDeviceName(value);
        return this;
    }

    @Override
    public OaUserRecord value7(String value) {
        setDeviceId(value);
        return this;
    }

    @Override
    public OaUserRecord value8(String value) {
        setOsVersion(value);
        return this;
    }

    @Override
    public OaUserRecord value9(String value) {
        setOaUserId(value);
        return this;
    }

    @Override
    public OaUserRecord value10(String value) {
        setOaUserName(value);
        return this;
    }

    @Override
    public OaUserRecord value11(Integer value) {
        setEnable(value);
        return this;
    }

    @Override
    public OaUserRecord value12(String value) {
        setPushId(value);
        return this;
    }

    @Override
    public OaUserRecord value13(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public OaUserRecord value14(Integer value) {
        setClientType(value);
        return this;
    }

    @Override
    public OaUserRecord value15(String value) {
        setLoginuuid(value);
        return this;
    }

    @Override
    public OaUserRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Integer value11, String value12, LocalDateTime value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OaUserRecord
     */
    public OaUserRecord() {
        super(OaUser.OA_USER);
    }

    /**
     * Create a detached, initialised OaUserRecord
     */
    public OaUserRecord(String id, String loginId, String password, String mobile, String clientModel, String deviceName, String deviceId, String osVersion, String oaUserId, String oaUserName, Integer enable, String pushId, LocalDateTime createTime, Integer clientType, String loginuuid) {
        super(OaUser.OA_USER);

        set(0, id);
        set(1, loginId);
        set(2, password);
        set(3, mobile);
        set(4, clientModel);
        set(5, deviceName);
        set(6, deviceId);
        set(7, osVersion);
        set(8, oaUserId);
        set(9, oaUserName);
        set(10, enable);
        set(11, pushId);
        set(12, createTime);
        set(13, clientType);
        set(14, loginuuid);
    }
}
