/*
 * This file is generated by jOOQ.
 */
package com.punch.entity.tables.records;


import com.punch.entity.tables.SysUser;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> implements Record6<String, String, String, Integer, String, Integer> {

    private static final long serialVersionUID = 164855015;

    /**
     * Setter for <code>punch.sys_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>punch.sys_user.id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>punch.sys_user.name</code>. 姓名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>punch.sys_user.name</code>. 姓名
     */
    @Size(max = 32)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>punch.sys_user.phone</code>. 手机号
     */
    public void setPhone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>punch.sys_user.phone</code>. 手机号
     */
    @Size(max = 16)
    public String getPhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>punch.sys_user.status</code>. 状态
     */
    public void setStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>punch.sys_user.status</code>. 状态
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>punch.sys_user.pwd</code>. 密码
     */
    public void setPwd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>punch.sys_user.pwd</code>. 密码
     */
    @Size(max = 128)
    public String getPwd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>punch.sys_user.is_admin</code>. 是否超级管理员
     */
    public void setIsAdmin(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>punch.sys_user.is_admin</code>. 是否超级管理员
     */
    @NotNull
    public Integer getIsAdmin() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, Integer, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, Integer, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysUser.SYS_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return SysUser.SYS_USER.NAME;
    }

    @Override
    public Field<String> field3() {
        return SysUser.SYS_USER.PHONE;
    }

    @Override
    public Field<Integer> field4() {
        return SysUser.SYS_USER.STATUS;
    }

    @Override
    public Field<String> field5() {
        return SysUser.SYS_USER.PWD;
    }

    @Override
    public Field<Integer> field6() {
        return SysUser.SYS_USER.IS_ADMIN;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPhone();
    }

    @Override
    public Integer component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getPwd();
    }

    @Override
    public Integer component6() {
        return getIsAdmin();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPhone();
    }

    @Override
    public Integer value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getPwd();
    }

    @Override
    public Integer value6() {
        return getIsAdmin();
    }

    @Override
    public SysUserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysUserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SysUserRecord value3(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public SysUserRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SysUserRecord value5(String value) {
        setPwd(value);
        return this;
    }

    @Override
    public SysUserRecord value6(Integer value) {
        setIsAdmin(value);
        return this;
    }

    @Override
    public SysUserRecord values(String value1, String value2, String value3, Integer value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(String id, String name, String phone, Integer status, String pwd, Integer isAdmin) {
        super(SysUser.SYS_USER);

        set(0, id);
        set(1, name);
        set(2, phone);
        set(3, status);
        set(4, pwd);
        set(5, isAdmin);
    }
}
