/*
 * This file is generated by jOOQ.
 */
package com.punch.entity.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OaPunchLog implements Serializable {

    private static final long serialVersionUID = -1767733694;

    private String        id;
    private String        userId;
    private String        memo;
    private LocalDateTime createTime;

    public OaPunchLog() {}

    public OaPunchLog(OaPunchLog value) {
        this.id = value.id;
        this.userId = value.userId;
        this.memo = value.memo;
        this.createTime = value.createTime;
    }

    public OaPunchLog(
        String        id,
        String        userId,
        String        memo,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.userId = userId;
        this.memo = memo;
        this.createTime = createTime;
    }

    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Size(max = 32)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Size(max = 1024)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OaPunchLog (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(memo);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
