/*
 * This file is generated by jOOQ.
 */
package com.punch.entity.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OaUser implements Serializable {

    private static final long serialVersionUID = -777070684;

    private String        id;
    private String        loginId;
    private String        password;
    private String        mobile;
    private String        clientModel;
    private String        deviceName;
    private String        deviceId;
    private String        osVersion;
    private String        oaUserId;
    private String        oaUserName;
    private Integer       enable;
    private String        pushId;
    private LocalDateTime createTime;

    public OaUser() {}

    public OaUser(OaUser value) {
        this.id = value.id;
        this.loginId = value.loginId;
        this.password = value.password;
        this.mobile = value.mobile;
        this.clientModel = value.clientModel;
        this.deviceName = value.deviceName;
        this.deviceId = value.deviceId;
        this.osVersion = value.osVersion;
        this.oaUserId = value.oaUserId;
        this.oaUserName = value.oaUserName;
        this.enable = value.enable;
        this.pushId = value.pushId;
        this.createTime = value.createTime;
    }

    public OaUser(
        String        id,
        String        loginId,
        String        password,
        String        mobile,
        String        clientModel,
        String        deviceName,
        String        deviceId,
        String        osVersion,
        String        oaUserId,
        String        oaUserName,
        Integer       enable,
        String        pushId,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.loginId = loginId;
        this.password = password;
        this.mobile = mobile;
        this.clientModel = clientModel;
        this.deviceName = deviceName;
        this.deviceId = deviceId;
        this.osVersion = osVersion;
        this.oaUserId = oaUserId;
        this.oaUserName = oaUserName;
        this.enable = enable;
        this.pushId = pushId;
        this.createTime = createTime;
    }

    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Size(max = 16)
    public String getLoginId() {
        return this.loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    @Size(max = 16)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Size(max = 16)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Size(max = 16)
    public String getClientModel() {
        return this.clientModel;
    }

    public void setClientModel(String clientModel) {
        this.clientModel = clientModel;
    }

    @Size(max = 16)
    public String getDeviceName() {
        return this.deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    @Size(max = 128)
    public String getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    @Size(max = 16)
    public String getOsVersion() {
        return this.osVersion;
    }

    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    @Size(max = 16)
    public String getOaUserId() {
        return this.oaUserId;
    }

    public void setOaUserId(String oaUserId) {
        this.oaUserId = oaUserId;
    }

    @Size(max = 16)
    public String getOaUserName() {
        return this.oaUserName;
    }

    public void setOaUserName(String oaUserName) {
        this.oaUserName = oaUserName;
    }

    public Integer getEnable() {
        return this.enable;
    }

    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    @Size(max = 255)
    public String getPushId() {
        return this.pushId;
    }

    public void setPushId(String pushId) {
        this.pushId = pushId;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OaUser (");

        sb.append(id);
        sb.append(", ").append(loginId);
        sb.append(", ").append(password);
        sb.append(", ").append(mobile);
        sb.append(", ").append(clientModel);
        sb.append(", ").append(deviceName);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(osVersion);
        sb.append(", ").append(oaUserId);
        sb.append(", ").append(oaUserName);
        sb.append(", ").append(enable);
        sb.append(", ").append(pushId);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
