/*
 * This file is generated by jOOQ.
 */
package com.punch.entity.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUser implements Serializable {

    private static final long serialVersionUID = -2107937893;

    private String  id;
    private String  name;
    private String  phone;
    private Integer status;
    private String  pwd;
    private Integer isAdmin;

    public SysUser() {}

    public SysUser(SysUser value) {
        this.id = value.id;
        this.name = value.name;
        this.phone = value.phone;
        this.status = value.status;
        this.pwd = value.pwd;
        this.isAdmin = value.isAdmin;
    }

    public SysUser(
        String  id,
        String  name,
        String  phone,
        Integer status,
        String  pwd,
        Integer isAdmin
    ) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.status = status;
        this.pwd = pwd;
        this.isAdmin = isAdmin;
    }

    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Size(max = 32)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 16)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Size(max = 128)
    public String getPwd() {
        return this.pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    @NotNull
    public Integer getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUser (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(status);
        sb.append(", ").append(pwd);
        sb.append(", ").append(isAdmin);

        sb.append(")");
        return sb.toString();
    }
}
